import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';

import { CodeOopsApiService, repositoryLabel } from '../../shared/data/codeoops-api.service';
import { httpErrorMessage, relativeTime } from '../../shared/data/format';
import { DocumentationJob } from '../../shared/data/models';
import { PageHeaderComponent } from '../../shared/layout/page-header.component';
import { CardComponent } from '../../shared/ui/card.component';
import { EmptyStateComponent } from '../../shared/ui/empty-state.component';
import { IconComponent } from '../../shared/ui/icon.component';
import { IconTileComponent } from '../../shared/ui/icon-tile.component';
import { SkeletonComponent } from '../../shared/ui/skeleton.component';

/**
 * Index of repositories that have documentation.
 *
 * Only jobs the backend reports as COMPLETED *and* `overview_available` are
 * listed — a job that has not finished, or one the backend has not verified
 * an artifact for, has no document, and listing it here would promise one
 * that does not exist.
 */
@Component({
  selector: 'co-documentation-index',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    RouterLink,
    PageHeaderComponent,
    CardComponent,
    EmptyStateComponent,
    IconComponent,
    IconTileComponent,
    SkeletonComponent,
  ],
  template: `
    <div class="page stack-lg">
      <co-page-header
        title="Documentation"
        subtitle="Overviews generated by CodeWiki, one per completed job."
        [crumbs]="[{ label: 'Dashboard', link: '/dashboard' }, { label: 'Documentation' }]"
      >
        <a page-actions class="btn btn--primary btn--sm" routerLink="/analyze">
          <co-icon name="plus" />
          <span>Analyze repository</span>
        </a>
      </co-page-header>

      @if (error(); as message) {
        <co-card>
          <p class="error" role="alert">{{ message }}</p>
        </co-card>
      } @else if (loading()) {
        <div class="grid">
          @for (card of [1, 2, 3]; track card) {
            <co-card>
              <div class="stack">
                <co-skeleton width="3rem" height="3rem" radius="var(--r-md)" />
                <co-skeleton width="70%" height="1rem" />
                <co-skeleton width="45%" height="0.8rem" />
              </div>
            </co-card>
          }
        </div>
      } @else if (documented().length) {
        <div class="grid">
          @for (job of documented(); track job.id) {
            <a class="doc" [routerLink]="['/documentation', job.id]">
              <co-icon-tile name="documentation" tone="red" size="lg" />
              <div class="doc__body">
                <p class="doc__title truncate">{{ nameOf(job) }}</p>
                <p class="doc__meta truncate">{{ job.branch || 'default branch' }}</p>
                <p class="doc__when">Generated {{ when(job) }}</p>
              </div>
              <co-icon name="arrow-right" class="doc__go" />
            </a>
          }
        </div>
      } @else {
        <co-card>
          <co-empty-state
            title="No documentation has been generated yet"
            message="When a job completes, its overview appears here."
            icon="documentation"
            tone="red"
          >
            <a class="btn btn--primary" routerLink="/analyze">
              <co-icon name="plus" />
              <span>Analyze a repository</span>
            </a>
          </co-empty-state>
        </co-card>
      }
    </div>
  `,
  styles: `
    :host { display: block; }

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(19rem, 1fr));
      gap: var(--s-4);
    }

    .doc {
      display: flex;
      align-items: center;
      gap: var(--s-4);
      padding: var(--s-5);
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--r-lg);
      box-shadow: var(--shadow-sm);
      transition: box-shadow var(--base) var(--ease), transform var(--base) var(--ease),
                  border-color var(--base) var(--ease);
    }

    .doc:hover {
      box-shadow: var(--shadow-md);
      border-color: var(--red-100);
      transform: translateY(-2px);
    }

    .doc__body { flex: 1; min-width: 0; }
    .doc__title { font-weight: 650; }
    .doc:hover .doc__title { color: var(--red-500); }
    .doc__meta { font-size: var(--t-sm); color: var(--text-secondary); }
    .doc__when { font-size: var(--t-xs); color: var(--text-muted); margin-top: 0.15rem; }

    .doc__go { width: 1.1rem; height: 1.1rem; color: var(--grey-300); flex: none; }
    .doc:hover .doc__go { color: var(--red-500); }

    .error { color: var(--err-600); text-align: center; padding: var(--s-6) 0; }
  `,
})
export class DocumentationIndexComponent {
  private readonly api = inject(CodeOopsApiService);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly jobs = signal<DocumentationJob[]>([]);
  protected readonly loading = signal(true);
  protected readonly error = signal<string | null>(null);

  protected readonly documented = computed(() =>
    this.jobs().filter(
      (job) => (job.status ?? '').toUpperCase() === 'COMPLETED' && job.overview_available === true,
    ),
  );

  constructor() {
    this.api
      .listJobs()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (jobs) => {
          this.jobs.set(jobs ?? []);
          this.loading.set(false);
        },
        error: (err: unknown) => {
          this.error.set(httpErrorMessage(err, 'The request for jobs did not complete.'));
          this.loading.set(false);
        },
      });
  }

  protected nameOf(job: DocumentationJob): string {
    return repositoryLabel(job);
  }

  protected when(job: DocumentationJob): string {
    return relativeTime(job.completed_at ?? job.created_at);
  }
}
