/**
 * View-side mirrors of the CodeOops backend payloads.
 *
 * Every field except `id` is optional. That is deliberate: the UI must render
 * correctly against whatever the backend actually returns, and a missing field
 * has to surface as "unknown", never as a fabricated default.
 *
 * Field names here match `app.schemas.job.JobResponse` /
 * `app.schemas.repository.RepositoryResponse` in the real backend, with two
 * exceptions the api service fills in itself from real data rather than
 * fabricating: `repository_url` / `repository_name` / `branch` (joined from
 * the job's `repository_id` against `GET /repositories`) and
 * `codewiki.duration_seconds` (computed from the two real CodeWiki
 * timestamps). `modules_total` / `modules_completed` are never set — this
 * backend has no per-module counts — so the progress bar always renders
 * indeterminate, which is correct, not broken.
 */

export type JobStatus =
  | 'QUEUED'
  | 'SUBMITTING'
  | 'GENERATING'
  | 'RETRIEVING'
  | 'COMPLETED'
  | 'FAILED';

export interface CodeWikiRunInfo {
  job_id?: string | null;
  status?: string | null;
  model?: string | null;
  started_at?: string | null;
  finished_at?: string | null;
  duration_seconds?: number | null;
}

export interface DocumentationJob {
  id: string;
  repository_id?: string | null;
  repository_url?: string | null;
  repository_name?: string | null;
  branch?: string | null;
  status?: JobStatus | string | null;

  created_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;

  error_code?: string | null;
  error_message?: string | null;

  /** True once the backend has a verified overview.md bound to this job. */
  overview_available?: boolean | null;

  /** Module counts drive the progress bar. Null means "not known yet". */
  modules_total?: number | null;
  modules_completed?: number | null;

  codewiki?: CodeWikiRunInfo | null;
}

/** One entry in the documentation rail. */
export interface DocumentationArtifact {
  /** File name as the backend stores it, e.g. `overview.md`. */
  name: string;
  title?: string | null;
  content?: string | null;
  bytes?: number | null;
  generated_at?: string | null;
}

export interface CreateJobRequest {
  repository_url: string;
}

/** Aggregate counters for the dashboard tiles. */
export interface DashboardStats {
  repositories?: number | null;
  jobs_total?: number | null;
  jobs_running?: number | null;
  jobs_completed?: number | null;
  jobs_failed?: number | null;
  documents?: number | null;
}

/**
 * The documents CodeOops has a slot for. Only `overview.md` is produced by the
 * current pipeline; the rest are rendered in the rail as unavailable so the
 * roadmap is visible without ever implying a file exists.
 */
export const DOCUMENT_SLOTS: ReadonlyArray<{
  name: string;
  title: string;
  description: string;
}> = [
  { name: 'overview.md', title: 'Overview', description: 'Repository overview generated by CodeWiki' },
  { name: 'architecture.md', title: 'Architecture', description: 'Component and dependency architecture' },
  { name: 'hld.md', title: 'High-Level Design', description: 'System-level design document' },
  { name: 'lld.md', title: 'Low-Level Design', description: 'Module-level design document' },
  { name: 'workflows.md', title: 'Workflows', description: 'End-to-end runtime workflows' },
];
