import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';

import { CodeOopsApiService, deriveStats, repositoryLabel } from '../../shared/data/codeoops-api.service';
import { httpErrorMessage, relativeTime } from '../../shared/data/format';
import { DocumentationJob } from '../../shared/data/models';
import { PageHeaderComponent } from '../../shared/layout/page-header.component';
import { CardComponent } from '../../shared/ui/card.component';
import { DonutChartComponent, DonutSegment } from '../../shared/ui/donut-chart.component';
import { EmptyStateComponent } from '../../shared/ui/empty-state.component';
import { IconComponent } from '../../shared/ui/icon.component';
import { IconTileComponent } from '../../shared/ui/icon-tile.component';
import { SkeletonComponent } from '../../shared/ui/skeleton.component';
import { StatTileComponent } from '../../shared/ui/stat-tile.component';
import {
  StatusPillComponent,
  humanStatus,
  toneForStatus,
} from '../../shared/ui/status-pill.component';

/**
 * Landing screen inside the shell.
 *
 * Every number on this page is counted from jobs the backend returned. While
 * the request is in flight the tiles show skeletons; if it fails they show a
 * dash and the error is stated. Nothing is ever filled in with a sample value.
 */
@Component({
  selector: 'co-dashboard',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    RouterLink,
    PageHeaderComponent,
    CardComponent,
    StatTileComponent,
    StatusPillComponent,
    DonutChartComponent,
    EmptyStateComponent,
    IconComponent,
    IconTileComponent,
    SkeletonComponent,
  ],
  template: `
    <div class="page stack-lg">
      <co-page-header
        title="Dashboard"
        subtitle="Repository documentation generated by the CodeWiki engine."
      >
        <div page-actions class="row">
          <button type="button" class="btn btn--ghost btn--sm" (click)="reload()" [disabled]="loading()">
            <co-icon name="refresh" />
            <span>Refresh</span>
          </button>
          <a class="btn btn--primary btn--sm" routerLink="/analyze">
            <co-icon name="plus" />
            <span>Analyze repository</span>
          </a>
        </div>
      </co-page-header>

      @if (error(); as message) {
        <div class="banner" role="alert">
          <co-icon name="alert" class="banner__icon" />
          <div>
            <p class="banner__title">Could not load dashboard data</p>
            <p class="banner__text">{{ message }}</p>
          </div>
          <button type="button" class="btn btn--ghost btn--sm" (click)="reload()">Try again</button>
        </div>
      }

      <!-- ---------------- stat tiles ---------------- -->
      <section class="grid-4">
        <co-stat-tile
          label="Repositories"
          icon="repositories"
          tone="red"
          [value]="stats().repositories ?? null"
          [loading]="loading()"
        />
        <co-stat-tile
          label="Jobs running"
          icon="jobs"
          tone="blue"
          [value]="stats().jobs_running ?? null"
          [loading]="loading()"
        />
        <co-stat-tile
          label="Completed"
          icon="check"
          tone="green"
          [value]="stats().jobs_completed ?? null"
          [loading]="loading()"
        />
        <co-stat-tile
          label="Failed"
          icon="alert"
          tone="amber"
          [value]="stats().jobs_failed ?? null"
          [loading]="loading()"
        />
      </section>

      <!-- ---------------- main split ---------------- -->
      <section class="split">
        <co-card title="Recent jobs" subtitle="Most recent documentation runs" flush>
          <a card-actions class="btn btn--quiet btn--sm" routerLink="/jobs">
            <span>View all</span>
            <co-icon name="arrow-right" />
          </a>

          @if (loading()) {
            <ul class="rows">
              @for (row of [1, 2, 3, 4]; track row) {
                <li class="rows__item rows__item--skeleton">
                  <co-skeleton width="2.5rem" height="2.5rem" radius="var(--r-md)" />
                  <div class="grow stack-sm">
                    <co-skeleton width="45%" height="0.9rem" />
                    <co-skeleton width="30%" height="0.75rem" />
                  </div>
                  <co-skeleton width="5rem" height="1.4rem" radius="var(--r-pill)" />
                </li>
              }
            </ul>
          } @else if (recentJobs().length) {
            <ul class="rows">
              @for (job of recentJobs(); track job.id) {
                <li class="rows__item">
                  <co-icon-tile name="git" [tone]="tileTone(job)" size="md" />
                  <a class="rows__main" [routerLink]="['/jobs', job.id]">
                    <span class="rows__title truncate">{{ label(job) }}</span>
                    <span class="rows__meta truncate">
                      {{ job.branch || 'default branch' }} · {{ when(job) }}
                    </span>
                  </a>
                  <co-status-pill [label]="statusText(job)" [tone]="statusTone(job)" />
                </li>
              }
            </ul>
          } @else {
            <co-empty-state
              title="No documentation runs yet"
              message="Submit a repository and CodeOops will send it to CodeWiki and bring the overview back here."
              icon="repositories"
              tone="red"
              compact
            >
              <a class="btn btn--primary btn--sm" routerLink="/analyze">
                <co-icon name="plus" />
                <span>Analyze a repository</span>
              </a>
            </co-empty-state>
          }
        </co-card>

        <div class="stack-lg">
          <co-card title="Job activity" subtitle="Every run this backend knows about">
            @if (loading()) {
              <co-skeleton width="100%" height="9.5rem" radius="var(--r-md)" />
            } @else {
              <co-donut-chart [segments]="activity()" centerLabel="Jobs" />
            }
          </co-card>

          <co-card title="Pipeline">
            <ul class="steps">
              @for (step of pipeline; track step.label) {
                <li class="steps__item">
                  <co-icon-tile [name]="step.icon" [tone]="step.tone" size="sm" />
                  <div>
                    <p class="steps__label">{{ step.label }}</p>
                    <p class="steps__desc">{{ step.description }}</p>
                  </div>
                </li>
              }
            </ul>
          </co-card>
        </div>
      </section>
    </div>
  `,
  styles: `
    :host { display: block; }

    .split {
      display: grid;
      grid-template-columns: minmax(0, 1.6fr) minmax(0, 1fr);
      gap: var(--s-6);
      align-items: start;
    }

    @media (max-width: 1080px) {
      .split { grid-template-columns: minmax(0, 1fr); }
    }

    .banner {
      display: flex;
      align-items: flex-start;
      gap: var(--s-3);
      padding: var(--s-4) var(--s-5);
      background: var(--err-50);
      border: 1px solid #FECDCA;
      border-radius: var(--r-lg);
    }

    .banner__icon { width: 1.25rem; height: 1.25rem; color: var(--err-600); flex: none; margin-top: 0.1rem; }
    .banner__title { font-weight: 650; color: var(--err-600); }
    .banner__text { font-size: var(--t-sm); color: var(--grey-700); }
    .banner > :last-child { margin-left: auto; flex: none; }

    .rows { display: grid; }

    .rows__item {
      display: flex;
      align-items: center;
      gap: var(--s-4);
      padding: var(--s-4) var(--s-5);
      border-top: 1px solid var(--border);
    }

    .rows__item:first-child { border-top: 0; }
    .rows__item:hover { background: var(--grey-50); }
    .rows__item--skeleton:hover { background: none; }

    .rows__main { display: grid; gap: 0.1rem; flex: 1; min-width: 0; }
    .rows__title { font-weight: 600; }
    .rows__item:hover .rows__title { color: var(--red-500); }
    .rows__meta { font-size: var(--t-sm); color: var(--text-muted); }

    .steps { display: grid; gap: var(--s-4); }
    .steps__item { display: flex; gap: var(--s-3); align-items: flex-start; }
    .steps__label { font-size: var(--t-sm); font-weight: 650; }
    .steps__desc { font-size: var(--t-sm); color: var(--text-secondary); }
  `,
})
export class DashboardComponent {
  private readonly api = inject(CodeOopsApiService);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly jobs = signal<DocumentationJob[]>([]);
  protected readonly loading = signal(true);
  protected readonly error = signal<string | null>(null);

  protected readonly pipeline = [
    {
      label: 'Repository intake',
      description: 'CodeOops validates the URL and creates a job.',
      icon: 'git' as const,
      tone: 'red' as const,
    },
    {
      label: 'CodeWiki analysis',
      description: 'Dependency graph and module clustering run deterministically.',
      icon: 'sitemap' as const,
      tone: 'blue' as const,
    },
    {
      label: 'Overview generation',
      description: 'Per-module summaries are reduced into a single overview.',
      icon: 'cpu' as const,
      tone: 'violet' as const,
    },
    {
      label: 'Artifact retrieval',
      description: 'overview.md is bound to this job and stored immutably.',
      icon: 'documentation' as const,
      tone: 'green' as const,
    },
  ];

  protected readonly stats = computed(() => deriveStats(this.jobs()));

  protected readonly recentJobs = computed(() => this.jobs().slice(0, 6));

  protected readonly activity = computed<DonutSegment[]>(() => {
    const s = this.stats();
    return [
      { label: 'Completed', value: s.jobs_completed ?? 0, tone: 'success' },
      { label: 'Running', value: s.jobs_running ?? 0, tone: 'progress' },
      { label: 'Failed', value: s.jobs_failed ?? 0, tone: 'danger' },
    ];
  });

  constructor() {
    this.reload();
  }

  protected reload(): void {
    this.loading.set(true);
    this.api
      .listJobs()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (jobs) => {
          this.jobs.set(jobs ?? []);
          this.error.set(null);
          this.loading.set(false);
        },
        error: (err: unknown) => {
          this.jobs.set([]);
          this.error.set(httpErrorMessage(err, 'The request for jobs did not complete.'));
          this.loading.set(false);
        },
      });
  }

  protected label(job: DocumentationJob): string {
    return repositoryLabel(job);
  }

  protected when(job: DocumentationJob): string {
    return relativeTime(job.created_at ?? job.started_at);
  }

  protected statusText(job: DocumentationJob): string {
    return humanStatus(job.status);
  }

  protected statusTone(job: DocumentationJob) {
    return toneForStatus(job.status);
  }

  protected tileTone(job: DocumentationJob): 'green' | 'blue' | 'amber' | 'grey' {
    switch (toneForStatus(job.status)) {
      case 'success':
        return 'green';
      case 'progress':
        return 'blue';
      case 'danger':
        return 'amber';
      default:
        return 'grey';
    }
  }
}
